// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqv5BAL8T1w5LZ2YHvk4lLXliSdxYyiWU',
    appId: '1:748977501894:web:54b245e4bb0f48620cc9c7',
    messagingSenderId: '748977501894',
    projectId: 'notification-b4bec',
    authDomain: 'notification-b4bec.firebaseapp.com',
    storageBucket: 'notification-b4bec.firebasestorage.app',
    measurementId: 'G-MB80M6PJFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4rj-eA9kWKversUXFjRcRvh9SbaAxr5Y',
    appId: '1:748977501894:android:672cb524cab930040cc9c7',
    messagingSenderId: '748977501894',
    projectId: 'notification-b4bec',
    storageBucket: 'notification-b4bec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNTBaRNIGG0Kkj2MjaOuUkchDPdoNBeEo',
    appId: '1:748977501894:ios:c4643c43d1b1a36a0cc9c7',
    messagingSenderId: '748977501894',
    projectId: 'notification-b4bec',
    storageBucket: 'notification-b4bec.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNTBaRNIGG0Kkj2MjaOuUkchDPdoNBeEo',
    appId: '1:748977501894:ios:c4643c43d1b1a36a0cc9c7',
    messagingSenderId: '748977501894',
    projectId: 'notification-b4bec',
    storageBucket: 'notification-b4bec.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqv5BAL8T1w5LZ2YHvk4lLXliSdxYyiWU',
    appId: '1:748977501894:web:a968a6eb2a45fd8c0cc9c7',
    messagingSenderId: '748977501894',
    projectId: 'notification-b4bec',
    authDomain: 'notification-b4bec.firebaseapp.com',
    storageBucket: 'notification-b4bec.firebasestorage.app',
    measurementId: 'G-YM96D3515W',
  );

}